version: "3.3"

services:
  teacher:
    container_name: teacher
    build:
      context: ./teacher
    ports:
      - "10020:10020"
    networks:
      kafka-net:
    depends_on:
      - kafka
    links:
      - "kafka:kafka"

  student:
    container_name: student
    build:
      context: ./student
    ports:
      - "10030:10030"
    networks:
      kafka-net:
    depends_on:
      - kafka
    links:
      - "kafka:kafka"

  analyzer:
    container_name: analyzer
    build:
      context: ./analyzer
    ports:
      - "10040:10040"
    networks:
      kafka-net:
    depends_on:
      - kafka
    links:
      - "kafka:kafka"

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    ports:
      - "2181:2181"
    networks:
      kafka-net:
    volumes:
      - zookeeper-persistence:/bitnami/zookeeper

  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    environment:
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
    ports:
      - "9092:9092"
    expose:
      - "9093"
    networks:
      kafka-net:
    depends_on:
      - zookeeper
    volumes:
      - kafka-persistence:/bitnami/kafka

volumes:
  kafka-persistence:
  zookeeper-persistence:

networks:
  kafka-net:
